//DO NOT EDIT THIS FILE

//This content is from https://www.tvmaze.com/
//specifically: https://api.tvmaze.com/shows/82/episodes


async function getShows() {
  const res = await fetch("https://api.tvmaze.com/shows");
  const showData = await res.json();
  return showData;
}

async function getAllEpisodes(id) {
  const res = await fetch(`https://api.tvmaze.com/shows/${id}/episodes`);
  const episodeData = await res.json();
  return episodeData;
}
